### ISSUE TITLE
Can't access Web UI (Linux/Docker)

### ISSUE THREAD

**Issue by Nitro112** [mr-guard/dayz-server-manager#185]
I have just now installed this using docker, but i can't access the Web UI.
Logging from docker indicates that the server is running fine.

I have tried 
http://127.0.0.1:2313
http://localhost:2313

```
dayz-1  | @2025-05-16T16:40:05.116Z | IMPORTANT | REST         | App listening on the http://127.0.0.1:2313
dayz-1  | @2025-05-16T16:40:05.116Z | IMPORTANT | IngameREST   | Ingame Rest API listening on the http://127.0.0.1:2312
dayz-1  | @2025-05-16T16:40:05.116Z | IMPORTANT | Bootstrap    | Server Manager initialized successfully
dayz-1  | @2025-05-16T16:40:05.116Z | IMPORTANT | Bootstrap    | Waiting for first server monitor tick..
dayz-1  | @2025-05-16T16:40:05.614Z | IMPORTANT | Monitor      | Server not found. Starting...
dayz-1  | @2025-05-16T16:40:05.616Z | INFO      | ServerStarte | Writing server cfg
dayz-1  | @2025-05-16T16:40:05.616Z | INFO      | ServerStarte | Adjusting dayzsetting.xml
dayz-1  | @2025-05-16T16:40:05.619Z | IMPORTANT | Monitor      | Server start initiated...
dayz-1  | @2025-05-16T16:40:07.113Z | INFO      | IngameReport | Server sent ingame report: 0 players, 43 vehicles
dayz-1  | @2025-05-16T16:41:35.715Z | INFO      | Monitor      | Server running...
```

docker-compose.yml
```

version: "3.8"

services:
  dayz:
    image: ghcr.io/mr-guard/dayz-server-manager:v3.10.0
    ports:
      - "2302-2312:2302-2312"
      - "2313:2313"
      - "8766:8766"
      - "27016:27016"
      - "80:8080" # publish the web server on port 8080 in your config
    volumes:
      - "./:/dayz" # make sure your server-manager.json is in there
    tty: true # needed for inputs
```
